{ config, pkgs, lib, ... }:

{
  home.username = "camen";
  home.homeDirectory = "/Users/camen";
  home.stateVersion = "24.11";

  # ============================================================
  # Packages (user-level)
  # ============================================================
  home.packages = with pkgs; [
    nerd-fonts.jetbrains-mono  # font for terminal / editor
    oh-my-zsh                  # zsh framework
  ];

  # ============================================================
  # Nix paths — bridges the gap between Nix store and dotfiles
  # This is the ONLY file generated by Nix. Everything else is
  # a plain dotfile that gets symlinked as-is.
  # ============================================================
  home.file.".nix-paths.sh" = {
    text = ''
      # Auto-generated by Nix — do not edit
      # Provides Nix store paths to plain dotfiles that need them
      export ZSH="${pkgs.oh-my-zsh}/share/oh-my-zsh"
    '';
  };

  # ============================================================
  # Git
  # ============================================================
  programs.git = {
    enable = true;
    signing.format = null;
    settings = {
      user = {
        name = "Camen";
        email = "29082904+camentree@users.noreply.github.com";
      };
      core.excludesfile = "${config.home.homeDirectory}/.gitignore_global";
      pull.rebase = false;
      push.autoSetupRemote = true;
      alias = {
        cm = "commit";
        co = "checkout";
        st = "status";
        br = "branch";
      };
    };
  };

  # ============================================================
  # Tmux — plugins managed by Nix, config is a plain dotfile
  # ============================================================
  programs.tmux = {
    enable = true;
    extraConfig = builtins.readFile ./dotfiles/tmux.conf;
    plugins = with pkgs.tmuxPlugins; [
      sensible
      resurrect
      continuum
      yank
      pain-control
      copycat
      open
      battery
      cpu
      vim-tmux-navigator
      net-speed
    ];
  };

  # ============================================================
  # Dotfiles — plain files, symlinked into ~/
  # Edit these directly, then run `rebuild`.
  # ============================================================
  home.file = {
    ".zshrc"             = { source = ./dotfiles/zshrc;             force = true; };
    ".zshenv"            = { source = ./dotfiles/zshenv;            force = true; };
    ".vimrc"             = { source = ./dotfiles/vimrc; };
    ".gitignore_global"  = { source = ./dotfiles/gitignore_global;  force = true; };
    ".prettierrc"        = { source = ./dotfiles/prettierrc;       force = true; };
    "agent-status.sh"    = { source = ./dotfiles/agent-status.sh; };
    ".ipython/profile_default/startup/00-imports.py" = { source = ./dotfiles/ipython_startup_imports.py; };

    # Starship prompt
    ".config/starship.toml" = { source = ./dotfiles/starship.toml; force = true; };

    # Neovim (lazy-lock.json is symlinked via activation script — it must be writable)
    ".config/nvim/init.lua"       = { source = ./dotfiles/nvim/init.lua;       force = true; };
    ".config/nvim/.stylua.toml"   = { source = ./dotfiles/nvim/.stylua.toml;   force = true; };

    # Ghostty terminal
    ".config/ghostty/config" = { source = ./dotfiles/ghostty; force = true; };

    # VSCode
    "Library/Application Support/Code/User/settings.json"    = { source = ./dotfiles/vscode/settings.json;    force = true; };
    "Library/Application Support/Code/User/keybindings.json" = { source = ./dotfiles/vscode/keybindings.json; force = true; };

    # Claude Code
    ".claude/settings.json" = { source = ./claude/settings.json; force = true; };
    ".claude/CLAUDE.md"     = { source = ./claude/CLAUDE.md;     force = true; };

    # SSH
    ".ssh/config" = {
      text = ''
        Host github.com
          AddKeysToAgent yes
          UseKeychain yes
          IdentityFile ~/.ssh/id_ed25519

        Host *
          AddKeysToAgent yes
          UseKeychain yes
      '';
    };

    # Local env file template (won't overwrite existing)
    ".zshenv.local" = {
      text = ''
        # Machine-specific environment variables and secrets
        # This file is gitignored and not tracked in dotfiles
      '';
      force = false;
    };
  };

  # ============================================================
  # Activation scripts — for files that need to be writable
  # ============================================================
  home.activation.neovimLazyLock = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD ln -sfn $VERBOSE_ARG \
      ${config.home.homeDirectory}/Projects/dotfiles/nix/dotfiles/nvim/lazy-lock.json \
      ${config.home.homeDirectory}/.config/nvim/lazy-lock.json
  '';
}
