{ config, pkgs, lib, ... }:

{
  home.username = "camen";
  home.homeDirectory = "/Users/camen";
  home.stateVersion = "24.11";

  # ============================================================
  # Packages (user-level)
  # ============================================================
  home.packages = with pkgs; [
    nerd-fonts.jetbrains-mono  # font for terminal / editor
    oh-my-zsh                  # zsh framework
  ];

  # ============================================================
  # Nix paths — bridges the gap between Nix store and dotfiles
  # This is the ONLY file generated by Nix. Everything else is
  # a plain dotfile that gets symlinked as-is.
  # ============================================================
  home.file.".nix-paths.sh" = {
    text = ''
      # Auto-generated by Nix — do not edit
      # Provides Nix store paths to plain dotfiles that need them
      export ZSH="${pkgs.oh-my-zsh}/share/oh-my-zsh"
    '';
  };

  # ============================================================
  # Git
  # ============================================================
  programs.git = {
    enable = true;
    signing.format = null;
    settings = {
      user = {
        name = "Camen";
        email = "29082904+camentree@users.noreply.github.com";
      };
      core.excludesfile = "${config.home.homeDirectory}/.gitignore_global";
      pull.rebase = false;
      push.autoSetupRemote = true;
      rerere.enabled = true;
      alias = {
        cm = "commit";
        co = "checkout";
        st = "status";
        br = "branch";
      };
    };
  };

  # ============================================================
  # Tmux — plugins managed by Nix, config is a plain dotfile
  # ============================================================
  programs.tmux = {
    enable = true;
    extraConfig = builtins.readFile ./home/tmux.conf;
    plugins = with pkgs.tmuxPlugins; [
      sensible
      resurrect
      continuum
      yank
      pain-control
      copycat
      open
      battery
      cpu
      vim-tmux-navigator
      net-speed
    ];
  };

  # ============================================================
  # Dotfiles — plain files, symlinked into ~/
  # Edit these directly, then run `rebuild`.
  # ============================================================
  home.file = {
    ".zshrc"             = { source = ./home/zshrc;             force = true; };
    ".zshenv"            = { source = ./home/zshenv;            force = true; };
    ".vimrc"             = { source = ./home/vimrc; };
    ".gitignore_global"  = { source = ./home/gitignore_global;  force = true; };
    ".prettierrc"        = { source = ./home/prettierrc;       force = true; };
    "agent-status.sh"    = { source = ./home/agent-status.sh; };
    ".ipython/profile_default/startup/00-imports.py" = { source = ./home/ipython_startup_imports.py; };

    # Starship prompt
    ".config/starship.toml" = { source = ./home/starship.toml; force = true; };

    # Neovim (lazy-lock.json is symlinked via activation script — it must be writable)
    ".config/nvim/init.lua"       = { source = ./home/nvim/init.lua;       force = true; };
    ".config/nvim/.stylua.toml"   = { source = ./home/nvim/.stylua.toml;   force = true; };

    # Ghostty terminal
    ".config/ghostty/config" = { source = ./home/ghostty; force = true; };

    # VSCode
    "Library/Application Support/Code/User/settings.json"    = { source = ./home/vscode/settings.json;    force = true; };
    "Library/Application Support/Code/User/keybindings.json" = { source = ./home/vscode/keybindings.json; force = true; };

  } // (
    let claudeRoot = toString ./claude;
    in builtins.listToAttrs (map (file:
      let rel = lib.removePrefix "${claudeRoot}/" (toString file);
      in {
        name = ".claude/${rel}";
        value = { source = file; force = true; };
      }
    ) (lib.filesystem.listFilesRecursive ./claude))
  ) // {

    # SSH
    ".ssh/config" = {
      text = ''
        Host github.com
          IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

        Host mac-intel-server
          HostName mac-intel-server.local
          User camen
          SetEnv TERM=xterm-256color

        Host *
          IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
      '';
    };

  };

  # ============================================================
  # Activation scripts — for files that need to be writable
  # ============================================================
  home.activation.sshAuthorizedKeys = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p ${config.home.homeDirectory}/.ssh
    $DRY_RUN_CMD chmod 700 ${config.home.homeDirectory}/.ssh
    echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJKrlOuiKfCW1tb/8PHXms+N8hSSxO1Rfw3YAVPA8lRW' > ${config.home.homeDirectory}/.ssh/authorized_keys
    $DRY_RUN_CMD chmod 600 ${config.home.homeDirectory}/.ssh/authorized_keys
  '';

  home.activation.neovimLazyLock = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD ln -sfn $VERBOSE_ARG \
      ${config.home.homeDirectory}/Projects/dotfiles/home/nvim/lazy-lock.json \
      ${config.home.homeDirectory}/.config/nvim/lazy-lock.json
  '';
}
