#!/bin/bash
set -e # exit on error


apt update
# check if python if not install
apt install python3.8 -y
apt install python3-pip -y
# check if git if not install
apt install git-all -y

# check ig gdal if not install
apt install gdal-bin -y

git config --global user.email "camenpihor@gmail.com"
git config --global user.name "camen"
git config credential.helper store

# memory monitoring
curl -sSO https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
bash add-monitoring-agent-repo.sh
apt install stackdriver-agent -y
service stackdriver-agent start